# Generated by Django 3.0.4 on 2020-03-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doctor', models.CharField(max_length=50)),
                ('specialist', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
    ]
