# Generated by Django 3.0.4 on 2020-04-02 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('doctor', '0002_auto_20200402_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_users', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('clock', models.DateTimeField()),
                ('diagnosis', models.CharField(max_length=255)),
                ('information', models.CharField(max_length=200)),
                ('id_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
            options={
                'db_table': 'medical_record',
            },
        ),
    ]
