# Generated by Django 3.0.4 on 2020-03-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_patient', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('profession', models.CharField(max_length=100)),
                ('name_kk', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
