# Generated by Django 3.0.4 on 2020-03-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_room', models.CharField(max_length=100)),
                ('sum_patient', models.IntegerField()),
            ],
            options={
                'db_table': 'room_patient',
            },
        ),
    ]
