# Generated by Django 3.0.4 on 2020-04-02 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rekam_medis', '0001_initial'),
        ('detail_rekam_medis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailmedicalrecord',
            name='id_medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekam_medis.MedicalRecord'),
        ),
    ]
